# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-10 07:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gamereplay',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gamereplay',
            name='shortid',
            field=hsreplaynet.utils.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True, verbose_name='Short ID'),
        ),
    ]
