# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-11 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160610_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgameplayer',
            name='losses',
            field=models.PositiveIntegerField(blank=True, help_text='Number of losses in the current game mode (current season)', null=True, verbose_name='Losses'),
        ),
        migrations.AddField(
            model_name='globalgameplayer',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Stars'),
        ),
        migrations.AddField(
            model_name='globalgameplayer',
            name='wins',
            field=models.PositiveIntegerField(blank=True, help_text='Number of wins in the current game mode (eg. ladder season, arena key...)', null=True, verbose_name='Wins'),
        ),
    ]
