# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160618_1127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gamereplay',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='gamereplay',
            name='reconnecting',
            field=models.BooleanField(default=False, help_text='Whether the player is reconnecting to an existing game', verbose_name='Is reconnecting'),
        ),
    ]
