# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160611_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereplay',
            name='exclude_in_aggregate_stats',
        ),
    ]
