# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-03 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160622_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgame',
            name='hearthstone_build',
            field=models.PositiveIntegerField(blank=True, help_text='Patch number at the time the game was played.', null=True),
        ),
    ]
