# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-08 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20160703_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalgame',
            options={'ordering': ('-match_start',)},
        ),
        migrations.RenameField(
            model_name='globalgame',
            old_name='match_start_timestamp',
            new_name='match_start',
        ),
        migrations.RemoveField(
            model_name='globalgame',
            name='hearthstone_build',
        ),
        migrations.AddField(
            model_name='globalgame',
            name='build',
            field=models.PositiveIntegerField(blank=True, help_text='Hearthstone build number the game was played on.', null=True),
        ),
        migrations.AlterField(
            model_name='gamereplay',
            name='upload_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='api.AuthToken'),
        ),
        migrations.AlterField(
            model_name='gamereplay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalgameplayer',
            name='deck_list',
            field=models.ForeignKey(help_text="As much as is known of the player's starting deck list.", on_delete=django.db.models.deletion.PROTECT, to='cards.Deck'),
        ),
        migrations.AlterField(
            model_name='globalgameplayer',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='globalgameplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
