# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-08 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20160708_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalgame',
            old_name='match_end_timestamp',
            new_name='match_end',
        ),
    ]
