# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-12 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import hsreplaynet.games.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20160710_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereplay',
            name='hide_player_names',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamereplay',
            name='visibility',
            field=hsreplaynet.utils.fields.IntEnumField(choices=[(1, 'Public'), (2, 'Unlisted')], default=1, validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.games.models.Visibility)]),
        ),
    ]
