# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.Adventure'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='client_player2_hero_card_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='wing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.Wing'),
        ),
        migrations.AlterField(
            model_name='wing',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scenarios.Adventure'),
        ),
        migrations.AlterField(
            model_name='wing',
            name='ownership_prereq_wing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.Wing'),
        ),
    ]
