# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-14 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20160714_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_gold',
        ),
    ]
