# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='key',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
