# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereplayupload',
            name='upload_timestamp',
        ),
    ]
