# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-12 02:49
from __future__ import unicode_literals

from django.db import migrations
import hsreplaynet.games.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160618_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_replay_visibility',
            field=hsreplaynet.utils.fields.IntEnumField(choices=[(1, 'Public'), (2, 'Unlisted')], default=1, validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.games.models.Visibility)], verbose_name='Default replay visibility'),
        ),
    ]
