# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-12 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_default_replay_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_account_request',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_replay_data',
            field=models.BooleanField(default=False),
        ),
    ]
