# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-08 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statsmeta',
            old_name='hearthstone_build',
            new_name='build',
        ),
    ]
