# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsmeta',
            name='region',
            field=models.CharField(max_length=4),
        ),
    ]
