# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hsreplaynet.fields
import hsreplaynet.uploads.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', hsreplaynet.fields.IntEnumField(choices=[(1, 'POWER_LOG'), (2, 'OUTPUT_TXT'), (3, 'HSREPLAY_XML')], validators=[hsreplaynet.fields.IntEnumValidator(hsreplaynet.uploads.models.GameUploadType)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upload_ip', models.GenericIPAddressField()),
                ('status', hsreplaynet.fields.IntEnumField(choices=[(0, 'UNKNOWN'), (1, 'PROCESSING'), (2, 'SERVER_ERROR'), (3, 'PARSING_ERROR'), (4, 'SUCCESS')], validators=[hsreplaynet.fields.IntEnumValidator(hsreplaynet.uploads.models.GameUploadStatus)])),
                ('tainted', models.BooleanField(default=False)),
                ('metadata', models.TextField()),
                ('file', models.FileField(upload_to=hsreplaynet.uploads.models._generate_key)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.GameReplayUpload')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AuthToken')),
            ],
        ),
        migrations.CreateModel(
            name='UploadEventProcessingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sns_topic_arn', models.CharField(max_length=100)),
                ('sns_message_id', models.CharField(max_length=100)),
                ('upload_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.GameUpload')),
            ],
        ),
    ]
