# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-10 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hsreplaynet.uploads.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', hsreplaynet.utils.fields.IntEnumField(choices=[(1, 'POWER_LOG'), (2, 'OUTPUT_TXT'), (3, 'HSREPLAY_XML')], validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.uploads.models.UploadEventType)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upload_ip', models.GenericIPAddressField()),
                ('status', hsreplaynet.utils.fields.IntEnumField(choices=[(0, 'UNKNOWN'), (1, 'PROCESSING'), (2, 'SERVER_ERROR'), (3, 'PARSING_ERROR'), (4, 'SUCCESS')], default=0, validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.uploads.models.UploadEventStatus)])),
                ('tainted', models.BooleanField(default=False)),
                ('metadata', models.TextField()),
                ('file', models.FileField(upload_to=hsreplaynet.uploads.models._generate_upload_path)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='games.GameReplay')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='api.AuthToken')),
            ],
        ),
    ]
