# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-13 22:02
from __future__ import unicode_literals

from django.db import migrations
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20160611_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='shortid',
            field=hsreplaynet.utils.fields.ShortUUIDField(blank=True, default=hsreplaynet.utils.fields._shortuuid, editable=False, max_length=22, unique=True, verbose_name='Short ID'),
        ),
    ]
