# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('uploads', '0002_auto_20160622_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='api.APIKey'),
        ),
    ]
